---
title: "R portfolio 0006-03"
author: "김건우"
date: '2019년 3월 8일 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r echo = FALSE}
library(dplyr)
library(ggplot2)

theme_set(theme_gray(base_family = "AppleGothic"))
par(family = "AppleGothic")
load("../data/data_eng.rda")
```

----
##### 본 문서는 R markdown으로 작성되었습니다.



#### 3번문제) 전교생의 국어성적과 영어성적에 대한 상관분석(Correlation)을 수행하시오.

  H0 : 우리 학교의 국어성적과 영어성적은 상관관계를 가지고 있다.
  H1 : 우리 학교의 국어성적과 영어성적은 상관관계를 가지고 있지 않다.

##### 1. 데이터 준비 

```{r}
library(dplyr)
data %>% select(kor, eng) -> sampledata2
head(sampledata2)
```

##### 2. 기술 통계 확인

```{r}
library(psych)
describe(sampledata2)
```

##### 3. 그래프로 데이터 확인하기

```{r}
pairs.panels(sampledata2)          
```

 +  국어와 영어의 상관계수는 -0.02임으로 -0.1 ~ 0.1 사이에 위치하여 무시할만한 관계를 가지고 있다고 본다.

##### 4. 상관분석
```{r}
cor(sampledata2, use = "complete.obs", method = c("pearson"))        

```


##### 5. 결과 그래프

```{r}
plot(kor ~ eng, data=sampledata2)
abline(lm(kor ~ eng, data=sampledata2), col='red')  
```


+ 실제 국어와 영어 간의 상관계수는 -0.01684502이며 이는 전술한 바와 같이 무시할만한 관계를 가지고 있다고 할 수 있다. 2개의 변수 간의 그래프의 기울기가 보여주듯이 이 둘 사이에는 특별한 관계가 없으며, 따라서 귀무가설을 기각한다.

