# Generated by Django 2.2.4 on 2020-01-18 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.IntegerField(choices=[(0, '구분없음'), (1, '남자'), (2, '여자')])),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=200)),
                ('oily', models.IntegerField(choices=[(1, '유익함'), (0, '영향없음'), (-1, '유해함')])),
                ('dry', models.IntegerField(choices=[(1, '유익함'), (0, '영향없음'), (-1, '유해함')])),
                ('sensitive', models.IntegerField(choices=[(1, '유익함'), (0, '영향없음'), (-1, '유해함')])),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(max_length=1023)),
                ('name', models.CharField(max_length=1023)),
                ('price', models.IntegerField(default=0)),
                ('monthly_sales', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programmers_test.Category')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programmers_test.Gender')),
                ('ingredient', models.ManyToManyField(to='programmers_test.Ingredient')),
            ],
        ),
    ]
