# Generated by Django 2.2.4 on 2020-01-20 06:14
import os
import json
from django.db import migrations
    

class Migration(migrations.Migration):

    dependencies = [
        ('programmers_test', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='ingredient_name',
            new_name='name',
        ),
    ]
