# Generated by Django 2.2.4 on 2020-01-20 08:23
import os
import json
from django.db import migrations


FILE_NAME = 'data/ingredient-data.json'
FILE_LOCATION = os.path.join(\
    os.path.abspath(os.path.join(os.path.dirname(__file__), os.pardir)), \
    FILE_NAME)

def get_json_data(FILE_LOCATION):
    with open(FILE_LOCATION) as f:
        data = json.load(f)
        result = []
        for datum in data:
            result.append(datum)
            if len(result) == 100:
                yield result
                result = []
        yield result

def insert_ingredient(apps, schema_editor):
    Ingredient = apps.get_model('programmers_test', 'Ingredient')
    json_data = get_json_data(FILE_LOCATION)

    nutrient_point = {'O': 1, '': 0, 'X': -1}

    for data in json_data:
        ingredient_list = []
        for datum in data:
            datum['oily'] = nutrient_point[datum['oily']]
            datum['dry'] = nutrient_point[datum['dry']]
            datum['sensitive'] = nutrient_point[datum['sensitive']]
            ingredient_list.append(Ingredient(**datum))
        print('\n\n\n ingredient_list >>>>> ', ingredient_list)
        Ingredient.objects.bulk_create(ingredient_list)

class Migration(migrations.Migration):

    dependencies = [
        ('programmers_test', '0003_auto_20200120_1709'),
    ]

    operations = [
        migrations.RunPython(insert_ingredient),
    ]
