# Generated by Django 2.2.4 on 2020-01-20 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmers_test', '0004_auto_20200120_1723'),
    ]

    operations = [
    ]
