# Generated by Django 2.2.4 on 2020-02-03 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmers_test', '0007_auto_20200121_1558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-id']},
        ),
    ]
