library(dplyr)
library(ggplot2)
library(gridExtra)
library(tibble)
library(stringi)
library(ggiraph)
library(devtools)
library(kormaps2014)
library(plotly)
library(dygraphs)
library(xts)

theme_set(theme_gray(base_family="AppleGothic"))
par(family = "AppleGothic")