library(dplyr)
library(ggplot2)
library(gridExtra)
library(tibble)
library(stringi)
library(ggiraph)
library(devtools)
library(kormaps2014)
library(plotly)
library(dygraphs)
library(xts)
library(sqldf)
library(RMySQL)
library(tm)
library("SnowballC")
library(RColorBrewer)
library(wordcloud)

library(twitteR); library(RCurl); library(RJSONIO); library(stringr)
library(streamR); library(ROAuth)
library(rJava); library(KoNLP)
library(arules); library(igraph); library(combinat)
library(arulesViz); library(visNetwork)

library(psych)
library(gmodels)

theme_set(theme_gray(base_family="AppleGothic"))
par(family = "AppleGothic")